version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    working_dir: /app/backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      target: frontend
    working_dir: /app/frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
