version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '10000:10000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
