version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    working_dir: /app/backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    build:
      context: .
      target: final
    ports:
      - '10000:10000'
    depends_on:
      - backend
