"""add normalized question models

Revision ID: 0aeb2e75f235
Revises: e9cb82b82a1b
Create Date: 2025-07-26 10:15:48.556982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aeb2e75f235'
down_revision: Union[str, Sequence[str], None] = 'e9cb82b82a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_grades_name'), 'grades', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_name'), table_name='grades')
    op.drop_column('grades', 'name')
    # ### end Alembic commands ###
