"""add normalized question models

Revision ID: 1314238654e2
Revises: 6aa775d9b3ef
Create Date: 2025-07-26 00:40:54.292634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1314238654e2'
down_revision: Union[str, Sequence[str], None] = '6aa775d9b3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.add_column('updated_questions', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'updated_questions', 'grades', ['grade_id'], ['id'])
    op.drop_column('updated_questions', 'grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updated_questions', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'updated_questions', type_='foreignkey')
    op.drop_column('updated_questions', 'grade_id')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    # ### end Alembic commands ###
