"""add normalized question models

Revision ID: 302580a029a8
Revises: c5c8d8650c00
Create Date: 2025-07-26 16:03:36.969255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302580a029a8'
down_revision: Union[str, Sequence[str], None] = 'c5c8d8650c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_question_attended', sa.Column('grade_id', sa.Integer(), nullable=False))
    op.add_column('user_question_attended', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_question_attended', 'grades', ['grade_id'], ['id'])
    op.create_foreign_key(None, 'user_question_attended', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_question_attended', type_='foreignkey')
    op.drop_constraint(None, 'user_question_attended', type_='foreignkey')
    op.drop_column('user_question_attended', 'subject_id')
    op.drop_column('user_question_attended', 'grade_id')
    # ### end Alembic commands ###
