"""add normalized question models

Revision ID: e9cb82b82a1b
Revises: fceccea5aa70
Create Date: 2025-07-26 07:00:22.730097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9cb82b82a1b'
down_revision: Union[str, Sequence[str], None] = 'fceccea5aa70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_question_topic_subject', 'updated_questions', ['question', 'topic_id', 'subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_question_topic_subject', 'updated_questions', type_='unique')
    # ### end Alembic commands ###
