"""add normalized question models

Revision ID: fceccea5aa70
Revises: 4e2d5bdb868f
Create Date: 2025-07-26 06:58:50.788661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fceccea5aa70'
down_revision: Union[str, Sequence[str], None] = '4e2d5bdb868f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_topic_name_subject', 'topics', ['name', 'subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_topic_name_subject', 'topics', type_='unique')
    # ### end Alembic commands ###
